<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ool_site"
 *
 * Auto generated by Extension Builder 2019-02-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sitewide Typo3 config',
    'description' => 'Sitewide Typo3 configuration extension',
    'category' => 'plugin',
    'author' => 'Fari',
    'author_email' => 'f.tardif.b@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
